import MessengerChat from "@/components/messenger-chat";
import "./globals.css";
import { Inter } from "next/font/google";
import CustomerChat from "@/components/customer-chat";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="main">
          <div className="main">{children}</div>
          {/* <MessengerChat /> */}
          <CustomerChat />
        </div>
      </body>
    </html>
  );
}
